### ISSUE TITLE
Setup sorting on ratings

### ISSUE THREAD

**Issue by acorncom** [ember-learn/ember-help-wanted#1]
We'll need to work out how to produce ratings (a rough gauge of how hard an item would be to do) before this can be done.  Would love feedback or ideas on how to produce that data (my current thought was to have an approximate number based on which repo the issue is for, but that's pretty rough)

**Comment by ijlee2** [comment]
I don't think adding support for rating issues will be in my immediate plans for the client and server apps. Let's open a new issue if, at a later point, rating issues can be a feasible problem.
