### ISSUE TITLE
Fix overlapping elements in mobile view

### ISSUE THREAD

**Issue by BradenLawrence** [ember-learn/ember-help-wanted#101]
I'd like to help out on this issue:

**Problem:** The Project name and Title become overlapped when viewed on mobile resolutions.
![ember-help-wanted_mobile](https://user-images.githubusercontent.com/17574170/48303664-d73e7c00-e4da-11e8-9768-37e7c12edd93.png)

**To do:** Update the CSS layout to stack the Project name underneath the Title at mobile resolutions.

**Future considerations:** The "Project, Title" column headers will not be needed if this is done, and should probably be hidden.

I see some work has already been done on making the app more responsive (ex: Issue #88, PR #96), but if no one is currently addressing this issue, I can start working on it.

**Comment by BradenLawrence** [comment]
I had a look at how the list is put together, and after seeing that it's arranged using a table, I think it's best for now to keep the Project Name on top of the Title at mobile sizes. There are ways to do this using CSS, but it's a bit dirty and breaks the table management structure. 

If we would like to do this in the future, we would have to restructure the list using divs/flexbox/etc.

**Comment by MelSumner** [comment]
Thank you for fixing this!
