### ISSUE TITLE
Improve home page

### ISSUE THREAD

**Issue by jenweber** [ember-learn/ember-help-wanted#104]
Currently, the "home" page of this app invites people to click on a nav bar item.

- [ ] add content section: "how to get started contributing to Ember" content, similar to what is in CONTRIBUTING.md guides. 
- [ ] add easily clickable graphics to go to the primary repos/labels
- [ ] add an h1 element: `<h1>Help Wanted</h1>` at the top of the page, between the navbar and the search box (should be inside a `<main>` element)

Guidelines: 
- CSS should be written in a mobile-first way
- try to use [ember-styleguide](https://github.com/ember-learn/ember-styleguide) if possible

**Comment by EndangeredMassa** [comment]
That sounds great to me!

**Comment by prasannavijayan** [comment]
I'll work on this issue.

**Comment by prasannavijayan** [comment]
@MelSumner @EndangeredMassa I just tried out a rough design with the checklist to be done. Please review and let me know if this is fine or we need to alter something.
![macbook pro](https://user-images.githubusercontent.com/3090884/49626698-1b04a280-fa01-11e8-8fe9-0a25e5a1f763.png)

**Comment by MelSumner** [comment]
Thank you for resolving this issue, @prasannavijayan 💯
