### ISSUE TITLE
Improve navbar

### ISSUE THREAD

**Issue by MelSumner** [ember-learn/ember-help-wanted#106]
In a mobile-first way, update the CSS for the navbar so it works appropriately on mobile devices.

**Comment by prasannavijayan** [comment]
I'll work on this issue.

**Comment by mansona** [comment]
I assume we're intendeing to use the Ember-Styleguide for this project @MelSumner?

**Comment by prasannavijayan** [comment]
@MelSumner @mansona Please do let me know if I wanted to update this according to ember styleguide, I will do it. For time being I've fixed with mobile menu addon.

**Comment by MelSumner** [comment]
:+1:
