### ISSUE TITLE
Add Issue Count

### ISSUE THREAD

**Issue by MelSumner** [ember-learn/ember-help-wanted#107]
It would be super useful to know how many issues are currently displayed in the view, especially if I am filtering by a label within a project. 

## What it looks like now
![image](https://user-images.githubusercontent.com/4587451/49251149-63f79e00-f3e6-11e8-91f6-9a024880b608.png)

## What it could look like
![image](https://user-images.githubusercontent.com/4587451/49251127-54785500-f3e6-11e8-921f-2783b5aff0f0.png)

**Comment by esbanarango** [comment]
@MelSumner I'll work on this one ☝️
