### ISSUE TITLE
help wanted app should use same navbar as emberjs.com

### ISSUE THREAD

**Issue by MelSumner** [ember-learn/ember-help-wanted#121]
Since the help-wanted app has been integrated into the emberjs.com website, it should use the same navbar as the rest of the emberjs.com website. 

Todo: 
- [ ] use the same navbar as emberjs.com. 
- [ ] add the filter buttons above the page title (attach the es-button class):
![image](https://user-images.githubusercontent.com/4587451/51792652-054a6880-217a-11e9-8bf5-4631a87bd697.png)

Any PRs to address this issue should please include screenshots to show what the implementation looks like.

**Comment by prasannavijayan** [comment]
I'll take this one.

**Comment by MelSumner** [comment]
Thank you for resolving this issue! :+1:
