### ISSUE TITLE
Navbar links aren't displaying on help wanted

### ISSUE THREAD

**Issue by MelSumner** [ember-learn/ember-help-wanted#124]
A previous PR made the correct edit of changing the filters out of the navbar and putting them in buttons. However, the navbar content that is displayed on the rest of the ember.js website isn't displaying properly on the help-wanted app. 

Screenshot: 
![image](https://user-images.githubusercontent.com/4587451/52537606-2c826780-2d2e-11e9-93fa-035315c0fe3c.png)

**Comment by optikalefx** [comment]
@MelSumner Where does `es-button` and `es-navbar` come from? Some addon I presume.

**Comment by MelSumner** [comment]
@optikalefx yes, the ember-learn/ember-styleguide addon. :+1:

**Comment by optikalefx** [comment]
I don't know if I can test a fix for this - it works locally. So I'll see if there is anything that might indicate that when this is live it would cause this.

![image](https://user-images.githubusercontent.com/926885/52585781-be0fd900-2e03-11e9-9536-751db8d6e031.png)

**Comment by optikalefx** [comment]
![image](https://user-images.githubusercontent.com/926885/52585811-cf58e580-2e03-11e9-8309-f9d29168b213.png)

**Comment by MelSumner** [comment]
@mansona can you look at this please?

**Comment by mansona** [comment]
Sure I'll take a look this week 👍

**Comment by mansona** [comment]
8 days later I find and fix the issue 😂 does that still count as "this week"? 😂
