### ISSUE TITLE
landing page inaccurately pulls in repos

### ISSUE THREAD

**Issue by MelSumner** [ember-learn/ember-help-wanted#126]
![image](https://user-images.githubusercontent.com/4587451/52583376-0e336f00-2df5-11e9-9dcb-efc4d215c538.png)

The query that is pulling in repos on the landing page is not pulling them in appropriately. As we can see in the screenshot, the first repo on the top left is "agendas" (https://github.com/ember-learn/agendas) and this repo does not have any issues labeled "help wanted" - or even any issues at all. 

To Fix: 
Ensure that the query that populates the landing page is written to pull in repos that have issues with the "help wanted" label on them.

**Comment by jaredgalanis** [comment]
@MelSumner I'll help with this one

**Comment by mschinis** [comment]
@MelSumner Looks like this one can now be closed.

**Comment by acorncom** [comment]
Thanks @mschinis
