### ISSUE TITLE
add ability to filter by Octane/help-wanted labels

### ISSUE THREAD

**Issue by MelSumner** [ember-learn/ember-help-wanted#129]
add ability to filter issues that have both the `Octane` label AND the `help wanted` label from the following orgs (specifically, issues that are tagged "Octane Meta" should not show up):

- emberjs (any repo)
- ember-learn (any repo) 
- ember-cli (any repo)

Once that is complete, add an Octane filter button to the filter button group.

**Comment by jaredgalanis** [comment]
@MelSumner I can help with this one as well, but need a little clarification.

When you say `following orgs`, does this mean you want buttons added for the orgs? Meaning these things:
![help_wanted_-_ember](https://user-images.githubusercontent.com/6305935/53020526-0ee78900-3425-11e9-9594-3194576acaae.png)

We have ember-learn already there, but does this involve adding pills for emberjs and ember-cli?

Additionally, I see that `Octane` is already showing up in the label filtering on the issues. I can look into excluding `Octane Meta`.

Relatedly, not sure if you had a chance to look at #128, but I could use a review on it.

**Comment by ppcano** [comment]
@jaredgalanis Thanks for helping out.

I talked with Melanie about this one.

We wanted to have an "Octane" button like the one you indicate on the picture (Core/RFCS/Learning...). If the user clicks the button, the site will show the issues with the specified filter:

> issues that have both the `Octane` label AND the `help wanted` on any repo of the `emberjs/ember-cli/ember-learn` orgs

It should be available under a specific URL, for example: `/octane` to be able to share it.

**Comment by MelSumner** [comment]
Thank you for resolving this issue! 👍
