### ISSUE TITLE
Remove Builds repo from help-wanted

### ISSUE THREAD

**Issue by mansona** [ember-learn/ember-help-wanted#131]
The [builds](https://github.com/ember-learn/builds) app has now been incorporated into the new [ember-website](https://github.com/ember-learn/ember-website) so we should no longer be showing issues in the help-wanted app

When we launch the ember-website we will do a process of porting issues and archiving the repo :+1: but for now we should stop showing them in help-wanted results

**Comment by jaredgalanis** [comment]
@mansona I'm game to help with this one
