### ISSUE TITLE
Move index route query to ember-help-wanted-server

### ISSUE THREAD

**Issue by jaredgalanis** [ember-learn/ember-help-wanted#133]
We may be better served having the query in the route `index.js`, which hits github's search api, residing on the ember-help-wanted-server where it can be cached and we don't risk running up against github's api rate limits as easily.

For more info see:
https://developer.github.com/v3/#rate-limiting
https://developer.github.com/v3/search/#rate-limit 

This work would correspond with this issue on the server:
https://github.com/ember-learn/ember-help-wanted-server/issues/15

I'm happy to work on this.

@MelSumner @mansona, how does this sound?

Relatedly, I'm noticing that we've been scoping the index route's query to ember-learn repos. There is no language that identifies this scope. Do we want to add language that clarifies or broaden the scope of the query to include other orgs? 

Keep in mind that if we maintain the current card-based design of the index page, but expanded out to other orgs beyond ember-learn, this page would grow rather long unless we arbitrarily impose a limit on the number of repos returned by the query.

**Comment by mansona** [comment]
So your two PRs are merged so I guess it is ok to close this issue 🤔 the only thing I would say is that we should probably create an issue that covers your second point about the cards on the homepage.

I would also add that they are not all that useful right now 🤔 the cards show "forks" for each repo... but that's not really the intent of this app. I would much prefer to see the number of help-wanted issues (or rather the number of issues that would show up in our filters) but I don't have an idea of how difficult that would be.

@jaredgalanis could you start another issue and we can start the discussion over there 👍

**Comment by jaredgalanis** [comment]
@mansona of course I'll create another issue now. sorry I didn't see this earlier.
