### ISSUE TITLE
Build a code snippet to pull from our backend to show items on the Ember Contributing page

### ISSUE THREAD

**Issue by acorncom** [ember-learn/ember-help-wanted#14]
I'm aiming to put a small table of info on the Community page (http://emberjs.com/community/) to replace the text under the header "In a Giving Mood?".  Should be a fairly simple Ajax call on the website ...

**Comment by MelSumner** [comment]
I believe that adding the "Help Wanted" link to the navbar also satisfies this feature request. :+1:
