### ISSUE TITLE
"All issues" filter takes you to the homepage

### ISSUE THREAD

**Issue by locks** [ember-learn/ember-help-wanted#156]
If you go to one of the projects (e.g. [https://help-wanted.emberjs.com/community](https://help-wanted.emberjs.com/community)), and you click "All Issues" you will be taken to the homepage of Help Wanted, which does not contain issues.

The behaviour should be fixed to list issues for all of the projects instead.

**Comment by neojp** [comment]
I don't see an "All issues" filter in the site. Should we close this issue or add the button?

![image](https://user-images.githubusercontent.com/127994/95739801-64efec80-0c59-11eb-8f77-aaf5b83d619e.png)

**Comment by ijlee2** [comment]
@neojp Let's close the issue for now. I'm working on updating the backend (https://github.com/ember-learn/ember-help-wanted-server) and want to coordinate the changes that will happen on the front.

I want to create 2 issues to update the list of filters in front and backend apps. Would you like to help with me with these?

**Comment by ijlee2** [comment]
Discussed a possible plan with @neojp on [Discord](https://discordapp.com/channels/480462759797063690/480523441082990612/765199025976508426). Let's close this issue for now.
