### ISSUE TITLE
Update ember-styleguide dependency to version 5.x

### ISSUE THREAD

**Issue by jenweber** [ember-learn/ember-help-wanted#162]
Right now, this app is on version 4. Version 5 has some breaking changes that need to be addressed. You can read about them [here](https://github.com/ember-learn/ember-styleguide/releases/tag/v5.0.0).

To do:
- update package.json to use version 5
- `yarn install` to update the package lock file
- Fix anything from the list of [breaking changes](https://github.com/ember-learn/ember-styleguide/releases/tag/v5.0.0)
- See how it looks and make any necessary adjustments
- Commit both package.json and the package lock files, together with your changed files
- open a pull request

**Comment by Kennie-create** [comment]
I'd like to help with this
