### ISSUE TITLE
Remove "Octane" button

### ISSUE THREAD

**Issue by jenweber** [ember-learn/ember-help-wanted#163]
Since Octane shipped a long time ago, this category has naturally dropped down to very few issues.

To-do:
- Remove the "Octane" button
- Search this codebase for the word "octane" and see if there is any code to remove
- See if any code needs to be removed in the help-wanted server https://github.com/ember-learn/ember-help-wanted-server and if there is, open a PR for that repository as well.

**Comment by ijlee2** [comment]
We can go ahead with removing the Octane button in the client app. Note, in the [server app](https://github.com/ember-learn/ember-help-wanted-server/pull/28), I'd like to add categories in a more flexible way, which may affect this issue.

**Comment by neojp** [comment]
I removed the button, and the references in the services/store with #168. Hopefully this should help closing this issue.

**Comment by ijlee2** [comment]
Yep, thank you for working on this issue!
