### ISSUE TITLE
Improve look and feel of the app

### ISSUE THREAD

**Issue by acorncom** [ember-learn/ember-help-wanted#17]
And make it fit better with the overall Ember site?

**Comment by acorncom** [comment]
Possible Tomster options (that we'll need to run by Leah first):

- Built with (http://emberjs.com/images/tomsters/builtwith.png)
- Code work (http://emberjs.com/images/tomsters/construction.png)

**Comment by ppcano** [comment]
I will look at this issue and use the [ember-styleguide UI addon](https://github.com/ember-learn/ember-styleguide)

**Comment by jenweber** [comment]
This app is now shiny & rebranded! Closed.
