### ISSUE TITLE
Fix lint errors

### ISSUE THREAD

**Issue by ijlee2** [ember-learn/ember-help-wanted#176]
## Background

After installing the latest `ember-template-lint` and `eslint` in #173, I suppressed new lint errors by adding exceptions to rules:

- [.eslintrc.js](https://github.com/ember-learn/ember-help-wanted/blob/747d54e1431cfb58fd85cff4fef62035d96686b3/.eslintrc.js#L23-L27)
- [.template-lintrc.js](https://github.com/ember-learn/ember-help-wanted/blob/919ee6af2d79ca55b76c9ef065b97c43493c6612/.template-lintrc.js#L5-L18)

## TODOs

- [ ] Remove the rule exceptions in `.eslintrc.js` one by one. If there's a fix that can be done easily (with respect to time and low risk of breaking the app), please do so.

- [ ] Remove the rule exceptions in `.template-lintrc.js` one by one. If there's a fix that can be done easily (with respect to time and low risk of breaking the app), please do so.

In general, you may want to check if there is a codemod that you can run. Because this app is relatively small, it may be better to manually fix the errors.

### eslint-plugin-ember

- [no-get](https://github.com/ember-cli/eslint-plugin-ember/blob/master/docs/rules/no-get.md)
- [require-computed-macros](https://github.com/ember-cli/eslint-plugin-ember/blob/master/docs/rules/require-computed-macros.md)
- [use-ember-data-rfc-395-imports](https://github.com/ember-cli/eslint-plugin-ember/blob/master/docs/rules/use-ember-data-rfc-395-imports.md)

### ember-template-lint

- [link-rel-noopener](https://github.com/ember-template-lint/ember-template-lint/blob/master/docs/rule/link-rel-noopener.md)
- [no-action](https://github.com/ember-template-lint/ember-template-lint/blob/master/docs/rule/no-action.md)
- [no-curly-component-invocation](https://github.com/ember-template-lint/ember-template-lint/blob/master/docs/rule/no-curly-component-invocation.md)
- [no-negated-condition](https://github.com/ember-template-lint/ember-template-lint/blob/master/docs/rule/no-negated-condition.md)
- [require-button-type](https://github.com/ember-template-lint/ember-template-lint/blob/master/docs/rule/require-button-type.md)
- [require-valid-alt-text](https://github.com/ember-template-lint/ember-template-lint/blob/master/docs/rule/require-valid-alt-text.md)

**Comment by ijlee2** [comment]
Assigned to @neojp .

**Comment by neojp** [comment]
`ember-template-lint` isn't throwing any errors now.

![image](https://user-images.githubusercontent.com/127994/95839925-8e6c4f00-0d11-11eb-85d9-23478b9e48e3.png)

**Comment by neojp** [comment]
`eslint` isn't throwing any errors now.

![image](https://user-images.githubusercontent.com/127994/95843221-739bd980-0d15-11eb-8cce-e63645b2dd18.png)

I will go ahead and submit a PR.
