### ISSUE TITLE
Keyword search is persistent when switching between pages

### ISSUE THREAD

**Issue by neojp** [ember-learn/ember-help-wanted#177]
Using the **keyword search** updates the `query` queryParam in the current controller filtering the results data. This works well the first time it's used. Once the user clicks in one of the buttons at the top, the query params get resetted, but the form is unchanged, and the results aren't filtered by the keyword in the form.

This might have been the reason the original code used plain `<a>` tags instead of `<LinkTo>` helpers.

We either need to clear the form when the route is updated, or keep the query param persistent when clicking the buttons. I'd prefer the latter. What do you think, @ijlee2?

## Screen recording
![y8fPfuTaV6](https://user-images.githubusercontent.com/127994/95842903-1bfd6e00-0d15-11eb-8adb-df50a847a0d9.gif)

**Comment by ijlee2** [comment]
Thanks for reporting this issue. The filter (Keyword) is currently broken because the client app doesn't have the most up-to-date list of repos and issues that the server app supports.

Let's comment out the form so that the user sees all issues for now. Does this sound okay with you?

**Comment by ijlee2** [comment]
@neojp I think I found what caused the bug that you described. The bug that I saw won't be fixed by the solution. I can create an issue for that later.
