### ISSUE TITLE
Publicize this app once we're ready for it

### ISSUE THREAD

**Issue by acorncom** [ember-learn/ember-help-wanted#18]
- [ ] Ember.JS Times
- [ ] EmberWeekly
- [ ] Ask Tom, other prominent Ember folks to tweet about it

**Comment by MelSumner** [comment]
@acorncom I think we're ready, especially since we want folks to use this to find DecEmber issues.

**Comment by MelSumner** [comment]
I'm going to close this issue because we've already publicized the app :+1: we'll continue to do so at EmberConf 2019 and beyond.
