### ISSUE TITLE
<FilterMenu> overflows on mobile

### ISSUE THREAD

**Issue by ijlee2** [ember-learn/ember-help-wanted#183]
## Problem

In #174, we increased the number of filters displayed from 5 to 11. This change allowed us to discover an overflow issue on mobile:

<img alt="The filters overflow on mobile" src="https://user-images.githubusercontent.com/16869656/96209337-f3ec5580-0f34-11eb-9778-d6a7a1c100bd.jpg" width="360" />

## TODOs

The app uses `ember-styleguide` for some of the styling (e.g. `.herounit` class in the `index` route template). I'm not sure yet if fixing the overflow issue can have a small scope. If you need help, please let us know!

- [ ] Fix the overflow issue.

- [ ] Please check that your solution works on multiple resolutions and browsers.

## References

- https://medium.com/@prowe214/tip-how-to-view-localhost-web-apps-on-your-phone-ad6b2c883a7c

**Comment by ijlee2** [comment]
Hi, everyone. I created this issue for [EmberFest Contributors Workshop](http://emberfest.eu/), to be held on October 16. Please allow a workshop participant the chance to claim and work on this issue first.

If the issue is still open after October 16, anyone is welcome to sign up for the issue. Thanks, and happy Hacktoberfest! 🎃

**Comment by fletcherrippon** [comment]
Hi can I be assigned this issue?

**Comment by ijlee2** [comment]
Hi, @fletcherrippon. Thank you for your interest in helping out with the Help Wanted app! If you have questions, feel free to let us know in this issue or over Ember Discord.

**Comment by fletcherrippon** [comment]
@ijlee2 Sorry I took so long was busy with some other stuff hope its what you wanted. 😁
