### ISSUE TITLE
2021 Contributors' Workshop: Allow filtering issues by query

### ISSUE THREAD

**Issue by ijlee2** [ember-learn/ember-help-wanted#196]
## Background

Currently, the user will encounter a runtime error when they try to filter issues by a **query** (a query is a string that we match against the issue title). To see an example, you can visit the following URL: https://help-wanted.emberjs.com/ember-learn?query=workshop

<img width="480" alt="runtime error message" src="https://user-images.githubusercontent.com/16869656/112800923-96763c00-9070-11eb-8a7d-40a9bc14118f.png">

A part of the reason that this bug has surfaced is the code complexity in `app/routes/issues.js`. The code also refers to `issue.body`, which does not exist. We'll try to address the bug in a small sequence of steps.

## Description

To help with reviewing your pull request, please make a commit after each step (don't forget to lint files after each step). There will be a total of 4 commits.

### Step 1

First, isolate and prevent the runtime error by replacing the problematic code.

In `app/routes/index.js`, create a function called `byTitle`. It accepts 1 argument, `query`, and **returns a filter function** that returns a Boolean.

```javascript
function byTitle(query) {
  return (issue) => {
    return true;
  };
}
```

Then, replace `this._matchWildcard(...)` with `this.byTitle` in the `_filter` function.

```javascript
// Before
this._matchWildcard(params.category, params.query)

// After
this.byTitle(params.query)
```

If you visit http://localhost:4200/ember-learn?query=workshop, you won't see a runtime error now. However, the filter returns all issues, rather than filtering them by the query.

### Step 2

Next, let's implement the function `byTitle`. I will leave you to the details, but the idea is to use JavaScript's `.toLowerCase()` and `.includes()` in order to do a case-insensitive comparison between `query` and `issue.title`.

I encourage you to make an early exit, i.e. when `query` is falsey, return `true`.

Now, when you visit http://localhost:4200/ember-learn, you will be able to filter issues by query.

### Step 3

Let's make sure that there will be no regression in the future. Please write an application test under `tests/acceptance/issues-test.js`.

In the test, you will use `fillIn` test helper to simulate entering a query. Afterwards, assert how many issues the user sees.

### Step 4

Let's clean up code. Please remove `_matchWildcard`, since it is no longer used.

**Comment by ijlee2** [comment]
Note, this issue is reserved for EmberConf contributors workshop. Please volunteer for the issue if you are participating in the workshop.

**Comment by ejfian-2020** [comment]
@ijlee2 I would like to take a stab at this issue.

**Comment by ijlee2** [comment]
@ejfian-2020 Thanks!

**Comment by ejfian-2020** [comment]
if query is falsey meaning if the user doesnot enter a text and just presses "Search" button , it should return the list of all issues correct ? 
`if(!query) return true;`

**Comment by ijlee2** [comment]
Yep, that's correct. You can also imagine a case, where the user hits the Backspace key to delete their current query.

So, the pseudocode would look like,

```javascript
if (!query) {
  return true;
}

// Do case-insensitive comparison now
```

**Comment by ejfian-2020** [comment]
heres the code so far 
`byTitle(query) {
    if(!query) return true;
    return (issue) => {
      return issue.title.toLowerCase().includes(query.toLowerCase())
    };
  },`

**Comment by ijlee2** [comment]
Ah, almost. I think it'd be,

```javascript
byTitle(query) {
  return (issue) => {
    if (!query) {
      return true;
    }

    return issue.title.toLowerCase().includes(query.toLowerCase());
  };
}
```

The last return statement may be difficult to read so we can also consider creating temporary variables for `issue.title.toLowerCase()` and `query.toLowerCase()` if you'd like.
