### ISSUE TITLE
2021 Contributors' Workshop: Convert 3 items to native class

### ISSUE THREAD

**Issue by ijlee2** [ember-learn/ember-help-wanted#197]
## Description

The following files show the classic Ember syntax:

- `app/adapters/application.js`
- `app/controllers/issues.js`
- `app/services/github-issues.js`

Since these files are relatively simple and have default unit tests, we can convert their syntax to native class with some confidence.

I encourage you to make 1 commit for each file, for a total of 3 commits.

## References

- https://guides.emberjs.com/release/models/customizing-adapters/
- https://guides.emberjs.com/release/routing/controllers/#toc_what-is-a-controller
- https://guides.emberjs.com/release/services/

**Comment by ijlee2** [comment]
Note, this issue is reserved for EmberConf contributors workshop. Please volunteer for the issue if you are participating in the workshop.

**Comment by pernambucano** [comment]
Hi, workshop participant here. I'd love to take a look at this!

**Comment by ijlee2** [comment]
@pernambucano Great, thank you for your help! Please let me know if you have any questions. You can reach me on Discord by chat at `@ijlee2`.

**Comment by pernambucano** [comment]
thanks a lot!

**Comment by acorncom** [comment]
Fixed by #198
