### ISSUE TITLE
Setup filtering on categories

### ISSUE THREAD

**Issue by acorncom** [ember-learn/ember-help-wanted#2]
preferably with a dropdown in place of the "Category" header, allowing choosing only one category instead of all of them.

Might be worth setting up a "table" component to help with this (and with #1 ).  Consider https://github.com/offirgolan/ember-light-table or possibly http://opensource.addepar.com/ember-table/#/overview  Would probably lean toward the former as it's in a newer, Ember 2.x style ...

**Comment by acorncom** [comment]
It would also be nice to be using `queryParams` for this so that these pages can be shared between folks

**Comment by MelSumner** [comment]
Since we've added filtering to the help-wanted app, I'm closing this issue. :+1:
