### ISSUE TITLE
Write some real acceptance tests

### ISSUE THREAD

**Issue by acorncom** [ember-learn/ember-help-wanted#22]

**Comment by lizzerdrix** [comment]
Do you have anything in mind for the kinds of tests you'd like to see? I notice there don't appear to be any at the moment, but just thought I'd check before I start writing anything 😛

**Comment by acorncom** [comment]
As I think about it, writing any acceptance tests right now is likely to be a major pain, due to EmberFire's lack of test support :-/  We're considering changing out the backend to something that would handle querying better, so it may be best to just wait on this temporarily ...  Thanks though!

**Comment by villander** [comment]
@acorncom And the acceptance tests with mirage? They are very real. Can I write acceptance tests with mirage?

**Comment by acorncom** [comment]
@villander Yes, we'd love to see acceptance tests written with Mirage, it's part of the reason we shifted from using EmberFire! 😀

**Comment by ppcano** [comment]
@hakilebara If none has taken this issue, I can write the acceptance tests.

**Comment by ppcano** [comment]
@MelSumner I think #77 should have closed this issue.
