### ISSUE TITLE
Help update this app to v4 of Ember

### ISSUE THREAD

**Issue by jenweber** [ember-learn/ember-help-wanted#224]
Upgrade instructions are in https://blog.emberjs.com/ember-4-0-released

This PR does not need to use Octane syntax in order to be merged. That can come later!

One incremental PR could be to update the app to v3.28 first, then address any breaking changes (if there are any) in followup PRs.

**Comment by ijlee2** [comment]
Hello. To provide additional background for new contributors, `ember-help-wanted` is fully Octane and has some tests to catch regressions.

I think you'll be able to safely upgrade the app from `3.27` to the latest `4.x` by running `ember-cli-update`, fixing potential merge conflicts, then running `yarn install` to update dependencies. (I do like the idea of updating the app to `3.28` first.)

**Comment by MehulKChaudhari** [comment]
Hey @jenweber I would like to work on this issue.

**Comment by jenweber** [comment]
Great, thank you! When you open a PR, please include a link to this issue in the PR description.
