### ISSUE TITLE
Work out user authentication piece

### ISSUE THREAD

**Issue by acorncom** [ember-learn/ember-help-wanted#65]
This helps finish off #16 

I think it'd be good to copy what Ember Twiddle is doing as much as possible (in the long run we might end up doing a shared add-on or something to make Github auth easier across all EmberJs.com "apps").

Things of interest that seem applicable to what we want to do:
- use Torii (https://github.com/Vestorly/torii)
- setup a torii adapter (https://github.com/ember-cli/ember-twiddle/blob/master/app/torii-adapters/application.js)
- consider using similar config to Twiddle (https://github.com/ember-cli/ember-twiddle/blob/master/config/environment.js#L64-L74)

We'll also want to work out what scope we would want to request for our Github OAuth app.  Full details on this here: https://developer.github.com/v3/oauth/#scopes Possible options:
- `(no scope)` - provides read-only info about the user (basic info, folks probably ok with giving us this info)
- `user:email` - gives us access to the user's email address (possibly useful for email notifications in the future? what use cases would we have?  worth discussing this further ...)
- `notifications` - not sure this has many practical benefits to what we're aiming to do in the long run

**Comment by acorncom** [comment]
@sivakumar-kailasam Thoughts on the scope questions above?

**Comment by sivakumar-kailasam** [comment]
@acorncom I'd like to ask for `user:email` but let users opt out of receiving notifications from within the app. Would help in the long run for these if they ever take shape - surveys, leaderboard updates, new workshop mailers. Thoughts?

**Comment by acorncom** [comment]
@sivakumar-kailasam seems like those types of features could be nice, but is that possibility worth the "why do they need my email address o_0?" question as we ask folks to login?  Theoretically we might be looking at 50-70% of the users of the tool logging in (probably more organizers than day-to-day users) ...

**Comment by sivakumar-kailasam** [comment]
Sure, I've seen services notifying users reasons for changing the required scope as they introduced new features. So I guess we can always do that.

**Comment by EndangeredMassa** [comment]
Is the current auth situation acceptable? No users have to auth and no repos have to do any special setup.

**Comment by sivakumar-kailasam** [comment]
Yes it is
