### ISSUE TITLE
Status?

### ISSUE THREAD

**Issue by aureliosaraiva** [ember-learn/ember-help-wanted#69]
@acorncom what is status this project? Active? Cancelled?

**Comment by sivakumar-kailasam** [comment]
@aureliosaraiva This project is in its very early stages and we unfortunately haven't added all the details about conversations(in the learning team meetings which are publicly documented) in this repo. 

We hope to give this project the attention it needs soon :) If you're interested in contributing to ember projects, please feel free to checkout the 'help wanted' labels on some of the other repos on this org along with the ember-cli & ember.js github orgs.

**Comment by acorncom** [comment]
@aureliosaraiva Another way of putting Siva's comments would be: it's inactive due to lack of folks to help push it along, we'd still love to see it done 😀 If you've got the time and interest, would love to discuss what is still blocking us on this to push it along.  Let me know!

**Comment by acorncom** [comment]
Going to close this for now, as @hakilebara is starting to think about things here further. @aureliosaraiva if you're interested in pitching in, would love to get your help too. We're collaborating on what we intend to do on this in Slack at `#st-help-wanted-board` or can discuss things on Github too ...
