### ISSUE TITLE
Label display is flakey when switching views

### ISSUE THREAD

**Issue by EndangeredMassa** [ember-learn/ember-help-wanted#85]
When you load the app, labels display properly next to issues. When you navigate to another category, some labels will not be rendered at all.

It's not clear why this happens. Look into the relationship between issues and labels as API resources.

---

API Documentation: https://developer.github.com/v3/

**Comment by prasannavijayan** [comment]
I will work on this issue..

**Comment by EndangeredMassa** [comment]
@prasannavijayan Sure thing!

There are a couple of things to consider:

1. There is a relationship between `github-issue` and `github-label` that you can see defined in those models. This was set up because the front-end used to be hitting github directly, which made this modelling mostly "just work" for the github response format. Now, however, the front-end hits a thin cache back-end instead. We could easily change the format of the API response, if that would help.

2. In Ember Data, we can see (with the ember inspector) that the labels all appear to be loaded. It's unclear why they aren't rendered, though.

3. The service `github-issues` is used to query the backend and find the right issues to show. This was also more necessary when we were hitting the github api directly, but now the front-end is hitting the back-end with a single call for the entire category of issues. We should probably re-assess the modelling here. We could create a category model that would hold all issues for a category, simplifying a lot of the front-end data logic here.

So, somewhere in that something is not getting where it needs to be. If you can find the bug and fix it directly, cool. If re-modeling around category resolves the issue anyway, also cool.
