### ISSUE TITLE
Make Navigation Responsive

### ISSUE THREAD

**Issue by EndangeredMassa** [ember-learn/ember-help-wanted#88]
The app is currently unusable on a mobile screen size. At the very least, the navigation tabs should flow down the screen. If we're feeling fancy, we can add a hamburger menu.

---

![image](https://user-images.githubusercontent.com/41545/46567349-58f92380-c8f7-11e8-8153-590a7ab661bc.png)

**Comment by ezebecke** [comment]
I will work on the hamburger menu!

**Comment by sivakumar-kailasam** [comment]
@ezebecke you might want to consider using https://github.com/offirgolan/ember-burger-menu

**Comment by EndangeredMassa** [comment]
resolved by https://github.com/ember-learn/ember-help-wanted/pull/96
