### ISSUE TITLE
CORS errors on site - no issues are shown

### ISSUE THREAD

**Issue by jbryson3** [ember-learn/ember-help-wanted#91]
https://ember-help-wanted.netlify.com/core

```Failed to load https://ember-help-wanted-server.herokuapp.com/github-issues?group=core: The 'Access-Control-Allow-Origin' header has a value 'https://help-wanted.emberjs.com' that is not equal to the supplied origin. Origin 'https://ember-help-wanted.netlify.com' is therefore not allowed access.```

![image](https://user-images.githubusercontent.com/675098/46695397-73741b00-cbdd-11e8-9568-d62fd99e213f.png)

I'm using Chrome 69

**Comment by sivakumar-kailasam** [comment]
@jbryson3 we've configured https://help-wanted.emberjs.com to be the domain for this app.  

If there's any doc that you referenced where we have forgot to update this info, do let us know.
