### ISSUE TITLE
Project Linkes are Missing

### ISSUE THREAD

**Issue by EndangeredMassa** [ember-learn/ember-help-wanted#93]
A recent deploy seems to have removed the project links from the issue tables.

Add a test for this and fix it.

---

Example:

![example](https://user-images.githubusercontent.com/41545/46881955-b3701380-ce12-11e8-9c89-b6a43067ba95.PNG)

**Comment by Ricool06** [comment]
Hey @EndangeredMassa, mind if I get assigned to this? Full disclosure, I've not used ember before but this might be a good start for me.

**Comment by Ricool06** [comment]
Fixed this, making a pull request in a sec. :+1:

**Comment by EndangeredMassa** [comment]
Thanks @Ricool06!
